apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: fastapi-app
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.containerPort }}
    nodePort: {{ .Values.service.nodePort }}
