apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  AWS_REGION: eu-central-1
  LOCAL_MODEL_PATH: tmp/model
  LOCAL_VERSION_PATH: tmp/model/model_version.txt
  MODEL_KEY: financiall-sentiment-analysis-models/model/
  S3_BUCKET: my-special-special-bucket
  VERSION_KEY: financiall-sentiment-analysis-models/model/model_version.txt
