name: CI/CD Pipeline for FastAPI Application

on:
  push:
    branches:
      - main

env:
  S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  MODEL_KEY: ${{ secrets.AWS_MODEL_KEY }}
  VERSION_KEY: ${{ secrets.AWS_VERSION_KEY }}
  LOCAL_MODEL_PATH: ${{ secrets.AWS_LOCAL_MODEL_PATH }}
  LOCAL_VERSION_PATH: ${{ secrets.AWS_LOCAL_VERSION_PATH }}
  GKE_CLUSTER_NAME: $${{ secrets.GKE_CLUSTER_NAME}}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          python -m pytest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Configure Docker to use Google Artifact Registry
        run: |
            gcloud auth configure-docker ${{ secrets.GKE_ZONE }}-docker.pkg.dev

      - name: Build and push Docker Image
        run: |
          IMAGE_URI=${{ secrets.GKE_ZONE }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-images/financial-news-sentiment:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GCP_PROJECT }}
  
      - name: Deploy to GKE using Helm
        run: |
          helm upgrade --install financial-news-api ./helm/api-chart \
            --set image.repository=${{ secrets.GKE_ZONE }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-images/financial-news-sentiment \
            --set image.tag=latest \
            --namespace default
            -f ./helm/api-chart/values.yaml \
            -f ./helm/api-chart/values-prod.yaml